# Assignment

Import numpy as np

In [1]:
import numpy as np

Make a python list => \[1,2,3,4,5\]

Convert it into numpy array and print it

In [2]:
listpy=[1,2,3,4,5]
listnum=np.array(listpy)
listnum

array([1, 2, 3, 4, 5])

Make a python matrix (3 x 3) => \[[1,2,3],[4,5,6],[7,8,9]\]

Convert it into numpy array and print it

In [3]:
pymat=[[1,2,3],[4,5,6],[7,8,9]]
pynum=np.array(pymat)
pynum

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Make a matrix (3 x 3) using built-in methods (like arange(), reshape() etc.):

\[ [1,3,5],

 [7,9,11],
 
 [13,15,17] \]

In [9]:
mat=np.arange(1,18,2).reshape(3,3)
mat

array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17]])

Create a numpy array with 10 random numbers from 0 to 10 (there should be few numbers greater than 1)

In [14]:
np.random.randn(10)+1

array([ 1.77633176,  2.50925711,  3.55943156,  0.91876551, -0.18709484,
        1.27803193, -0.7621064 ,  0.99914437,  1.78802993,  2.45935986])

Create numpy array => \[1,2,3,4,5\] and convert it to 2D array with 5 rows

In [22]:
num=np.arange(1,6).reshape(5,1)
num

array([[1],
       [2],
       [3],
       [4],
       [5]])

Print the shape of the above created array

In [24]:
num.shape

(5, 1)

Create a numpy array with 10 elements in it. Access and print its 3rd, 4th and 9th element.

In [47]:
num1=np.arange(1,11)
num1[2],num1[3],num1[8]

(3, 4, 9)

Print alternate elements of that array

In [49]:
num1[2],num1[3],num1[8] = [2,5,7]
num1

array([ 1,  2,  2,  5,  5,  6,  7,  8,  7, 10])

Change last 3 elements into 100 using broadcasting and print

In [54]:
num1[7:]=[100]
num1

array([  1,   2,   2,   5,   5,   6,   7, 100, 100, 100])

Create a 5 x 5 matrix (fill it with any element you like), print it.

Then print the middle (3 x 3) matrix.

In [63]:
mat1=np.arange(1,26).reshape(5,5)
mat1[1:4,1:4]
#mat1

array([[ 7,  8,  9],
       [12, 13, 14],
       [17, 18, 19]])